algorithmComparison(algorithms: [HIVDB, REGA, ANRS]) {
        drugClass {
		name
	}
	drugScores {
		drug {name, displayAbbr}
		algorithm
        	SIR
        	interpretation
       		explanation
	}
}
